# Generated by Django 3.0 on 2020-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
